apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
      - name: logging-service
        image: your-docker-image:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        volumeMounts:
        - name: logs-db
          mountPath: /app/logs.db
      volumes:
      - name: logs-db
        persistentVolumeClaim:
          claimName: logs-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
spec:
  selector:
    app: logging-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi